/**
 * Resolution Engine
 * Creates and manages resolutions for detected risks
 * Rule-based: 1 Risk = 1 Default Resolution
 */

import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import type {
  Risk,
  Resolution,
  TrustMetrics,
  AutonomyLevel,
  FamilyRules,
  L4CheckResult,
} from '../types/index.js';

const db = () => getFirestore();

// ============================================
// Resolution Configuration
// ============================================

// Delay times based on autonomy level
const DELAY_CONFIG: Record<AutonomyLevel, number> = {
  L2: 15, // 15 minutes for suggestions
  L3: 10, // 10 minutes with approval
  L4: 5,  // 5 minutes for autonomous
};

// ============================================
// Main Resolution Creation
// ============================================

export interface CreateResolutionResult {
  resolution: Resolution;
  autonomyLevel: AutonomyLevel;
}

export async function createResolutionForRisk(
  risk: Risk,
  userId: string
): Promise<CreateResolutionResult> {
  // Get family rules
  const rules = await getFamilyRules(risk.familyId);
  if (!rules) {
    throw new Error(`No family rules found for family ${risk.familyId}`);
  }

  // Get trust metrics to determine autonomy level
  const trustMetrics = await getTrustMetrics(userId);
  const autonomyLevel = determineAutonomyLevel(risk, trustMetrics);

  // Calculate timing
  const delayMinutes = DELAY_CONFIG[autonomyLevel];
  const scheduledAt = new Date(Date.now() + delayMinutes * 60 * 1000);
  const vetoDeadline = new Date(scheduledAt.getTime() - 60 * 1000); // 1 minute before execution

  // Determine recipient based on risk type
  let recipient: string;
  if (risk.type === 'pickup_handoff') {
    // For handoff, notify the available member(s)
    const context = risk.context as { availableMembers?: string[] };
    recipient = context.availableMembers?.[0] || rules.partnerName;
  } else {
    // For other risks, use default rules
    recipient = rules.defaultPickupPerson === 'user' ? rules.partnerName : 'user';
  }

  // Create resolution
  const resolution: Resolution = {
    id: generateResolutionId(risk.id),
    riskId: risk.id,
    familyId: risk.familyId,
    action: 'send_message',
    autonomyLevel,

    // Recipient
    recipient,
    recipientChannel: 'push', // MVP: push notification only

    // Message will be generated by Language Actuator
    message: '', // Placeholder - filled by Language Actuator

    // Timing
    scheduledAt: Timestamp.fromDate(scheduledAt),
    vetoDeadline: Timestamp.fromDate(vetoDeadline),
    delayMinutes,

    // Status
    status: 'scheduled',
    createdAt: Timestamp.now(),
  };

  // Save resolution
  await db().collection('resolutions').doc(resolution.id).set(resolution);

  // Update risk status
  await db().collection('risks').doc(risk.id).update({
    status: 'resolving',
  });

  return { resolution, autonomyLevel };
}

// ============================================
// Autonomy Level Determination
// ============================================

function determineAutonomyLevel(
  risk: Risk,
  trustMetrics: TrustMetrics | null
): AutonomyLevel {
  // No trust history = start at L2
  if (!trustMetrics) {
    return 'L2';
  }

  // Check L4 eligibility
  const l4Check = checkL4Eligibility(risk, trustMetrics);
  if (l4Check.eligible) {
    return 'L4';
  }

  // Check L3 eligibility (lower bar than L4)
  if (trustMetrics.successRate >= 0.7 && trustMetrics.recentVetoCount <= 3) {
    return 'L3';
  }

  // Default to L2
  return 'L2';
}

function checkL4Eligibility(
  risk: Risk,
  trustMetrics: TrustMetrics
): L4CheckResult {
  const reasons: string[] = [];
  let eligible = true;

  // Check success rate
  if (trustMetrics.successRate < 0.9) {
    eligible = false;
    reasons.push(`Success rate ${(trustMetrics.successRate * 100).toFixed(0)}% < 90%`);
  }

  // Check recent vetos
  if (trustMetrics.recentVetoCount >= 2) {
    eligible = false;
    reasons.push(`Recent vetos ${trustMetrics.recentVetoCount} >= 2`);
  }

  // Check risk type is allowed for L4
  const allowedTypes = ['pickup_conflict', 'pickup_handoff', 'schedule_overlap'];
  if (!allowedTypes.includes(risk.type)) {
    eligible = false;
    reasons.push(`Risk type "${risk.type}" not allowed for L4`);
  }

  // Note: Third-party involvement check would go here
  // For MVP, we assume no third parties

  if (eligible) {
    reasons.push('All L4 conditions met');
  }

  return { eligible, reasons };
}

// ============================================
// Resolution Execution
// ============================================

export async function executeResolution(resolutionId: string): Promise<boolean> {
  const resolutionRef = db().collection('resolutions').doc(resolutionId);
  const doc = await resolutionRef.get();

  if (!doc.exists) {
    throw new Error(`Resolution ${resolutionId} not found`);
  }

  const resolution = doc.data() as Resolution;

  // Check if already executed or vetoed
  if (resolution.status !== 'scheduled') {
    console.log(`Resolution ${resolutionId} already ${resolution.status}`);
    return false;
  }

  // Check if past veto deadline
  const now = Timestamp.now();
  if (now.toMillis() < resolution.vetoDeadline.toMillis()) {
    console.log(`Resolution ${resolutionId} still within veto window`);
    return false;
  }

  // Execute the action (send message)
  // In a real implementation, this would call the notification service
  console.log(`Executing resolution ${resolutionId}: Sending message to ${resolution.recipient}`);

  // Update resolution status
  await resolutionRef.update({
    status: 'executed',
    executedAt: Timestamp.now(),
  });

  // Update risk status
  await db().collection('risks').doc(resolution.riskId).update({
    status: 'resolved',
  });

  // Log the action
  await logAction(resolution, 'executed');

  // Update trust metrics
  await updateTrustMetrics(resolution, false);

  return true;
}

// ============================================
// Veto Handling
// ============================================

export async function vetoResolution(
  resolutionId: string,
  reason?: string
): Promise<boolean> {
  const resolutionRef = db().collection('resolutions').doc(resolutionId);
  const doc = await resolutionRef.get();

  if (!doc.exists) {
    throw new Error(`Resolution ${resolutionId} not found`);
  }

  const resolution = doc.data() as Resolution;

  // Check if can still be vetoed
  if (resolution.status !== 'scheduled') {
    console.log(`Cannot veto resolution ${resolutionId}: already ${resolution.status}`);
    return false;
  }

  const now = Timestamp.now();
  if (now.toMillis() > resolution.vetoDeadline.toMillis()) {
    console.log(`Cannot veto resolution ${resolutionId}: past deadline`);
    return false;
  }

  // Veto the resolution
  await resolutionRef.update({
    status: 'vetoed',
    vetoedAt: Timestamp.now(),
    vetoReason: reason || 'User vetoed',
  });

  // Update risk back to pending
  await db().collection('risks').doc(resolution.riskId).update({
    status: 'pending',
  });

  // Log the action
  await logAction(resolution, 'vetoed');

  // Update trust metrics (count as veto)
  await updateTrustMetrics(resolution, true);

  return true;
}

// ============================================
// Action Logging
// ============================================

async function logAction(
  resolution: Resolution,
  outcome: 'executed' | 'vetoed'
): Promise<void> {
  const risk = await db().collection('risks').doc(resolution.riskId).get();
  const riskData = risk.data() as Risk;

  const actionLog = {
    id: `log_${resolution.id}`,
    familyId: resolution.familyId,
    riskId: resolution.riskId,
    resolutionId: resolution.id,
    what: `${outcome === 'executed' ? 'Sent' : 'Did not send'} message to ${resolution.recipient}`,
    why: riskData.context.description,
    message: resolution.message,
    autonomyLevel: resolution.autonomyLevel,
    outcome,
    wasVetoed: outcome === 'vetoed',
    timestamp: Timestamp.now(),
  };

  await db().collection('actionLogs').doc(actionLog.id).set(actionLog);
}

// ============================================
// Trust Metrics
// ============================================

async function getTrustMetrics(userId: string): Promise<TrustMetrics | null> {
  const doc = await db().collection('trustMetrics').doc(userId).get();
  if (!doc.exists) {
    return null;
  }
  return doc.data() as TrustMetrics;
}

async function updateTrustMetrics(
  resolution: Resolution,
  wasVetoed: boolean
): Promise<void> {
  // Get user ID from family (simplified - in real app, would track per-user)
  const familyDoc = await db().collection('familyRules').doc(resolution.familyId).get();
  if (!familyDoc.exists) return;

  const userId = resolution.familyId; // Simplified: use familyId as userId for MVP
  const metricsRef = db().collection('trustMetrics').doc(userId);
  const doc = await metricsRef.get();

  if (!doc.exists) {
    // Create initial metrics
    const newMetrics: TrustMetrics = {
      userId,
      familyId: resolution.familyId,
      totalActions: 1,
      executedActions: wasVetoed ? 0 : 1,
      vetoedActions: wasVetoed ? 1 : 0,
      successRate: wasVetoed ? 0 : 1,
      recentVetoCount: wasVetoed ? 1 : 0,
      currentAutonomyLevel: 'L2',
      l4Eligible: false,
      lastUpdated: Timestamp.now(),
    };
    await metricsRef.set(newMetrics);
    return;
  }

  const metrics = doc.data() as TrustMetrics;

  // Update counts
  metrics.totalActions++;
  if (wasVetoed) {
    metrics.vetoedActions++;
    metrics.recentVetoCount = Math.min(metrics.recentVetoCount + 1, 10);
  } else {
    metrics.executedActions++;
    // Decay recent veto count on success
    metrics.recentVetoCount = Math.max(0, metrics.recentVetoCount - 0.5);
  }

  // Recalculate success rate
  metrics.successRate = metrics.executedActions / metrics.totalActions;

  // Update L4 eligibility
  metrics.l4Eligible = metrics.successRate >= 0.9 && metrics.recentVetoCount < 2;

  // Update current autonomy level
  if (metrics.l4Eligible) {
    metrics.currentAutonomyLevel = 'L4';
  } else if (metrics.successRate >= 0.7) {
    metrics.currentAutonomyLevel = 'L3';
  } else {
    metrics.currentAutonomyLevel = 'L2';
  }

  metrics.lastUpdated = Timestamp.now();

  await metricsRef.update({
    totalActions: metrics.totalActions,
    executedActions: metrics.executedActions,
    vetoedActions: metrics.vetoedActions,
    successRate: metrics.successRate,
    recentVetoCount: metrics.recentVetoCount,
    currentAutonomyLevel: metrics.currentAutonomyLevel,
    l4Eligible: metrics.l4Eligible,
    lastUpdated: metrics.lastUpdated,
  });
}

// ============================================
// Query Functions
// ============================================

export async function getScheduledResolutions(
  familyId: string
): Promise<Resolution[]> {
  const snapshot = await db()
    .collection('resolutions')
    .where('familyId', '==', familyId)
    .where('status', '==', 'scheduled')
    .orderBy('scheduledAt')
    .get();

  return snapshot.docs.map((doc) => doc.data() as Resolution);
}

export async function getResolutionsForRisk(riskId: string): Promise<Resolution[]> {
  const snapshot = await db()
    .collection('resolutions')
    .where('riskId', '==', riskId)
    .get();

  return snapshot.docs.map((doc) => doc.data() as Resolution);
}

// ============================================
// Helper Functions
// ============================================

async function getFamilyRules(familyId: string): Promise<FamilyRules | null> {
  const doc = await db().collection('familyRules').doc(familyId).get();
  if (!doc.exists) {
    return null;
  }
  return doc.data() as FamilyRules;
}

function generateResolutionId(riskId: string): string {
  const timestamp = Date.now();
  return `res_${riskId}_${timestamp}`;
}
