/**
 * Resolution Engine
 * Creates and manages resolutions for detected risks
 * Rule-based: 1 Risk = 1 Default Resolution
 */

import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import type {
  Risk,
  Resolution,
  AutonomyLevel,
  FamilyRules,
} from '../types/index.js';
import { sendPushToUser } from '../notifications/index.js';
import { decideAutonomyLevel, recordOutcome } from '../autonomy-governor/index.js';

const db = () => getFirestore();

// ============================================
// Resolution Configuration
// ============================================

// Delay times based on autonomy level
const DELAY_CONFIG: Record<AutonomyLevel, number> = {
  L2: 15, // 15 minutes for suggestions
  L3: 10, // 10 minutes with approval
  L4: 5,  // 5 minutes for autonomous
};

// ============================================
// Main Resolution Creation
// ============================================

export interface CreateResolutionResult {
  resolution: Resolution;
  autonomyLevel: AutonomyLevel;
}

export async function createResolutionForRisk(
  risk: Risk
): Promise<CreateResolutionResult> {
  // Get family rules
  const rules = await getFamilyRules(risk.familyId);
  if (!rules) {
    throw new Error(`No family rules found for family ${risk.familyId}`);
  }

  // Autonomy Governor decides how much autonomy this risk's category has earned
  const autonomyLevel = await decideAutonomyLevel(risk);

  // Calculate timing
  const delayMinutes = DELAY_CONFIG[autonomyLevel];
  const scheduledAt = new Date(Date.now() + delayMinutes * 60 * 1000);
  const vetoDeadline = new Date(scheduledAt.getTime() - 60 * 1000); // 1 minute before execution

  // Determine recipient based on risk type
  let recipient: string;
  if (risk.type === 'pickup_handoff') {
    // For handoff, notify the available member(s)
    const context = risk.context as { availableMembers?: string[] };
    recipient = context.availableMembers?.[0] || rules.partnerName;
  } else if (risk.type === 'subscription_waste') {
    // Subscription waste is a household-money decision — surface it to the
    // primary user, who decides whether to cancel.
    recipient = 'user';
  } else {
    // For other risks, use default rules
    recipient = rules.defaultPickupPerson === 'user' ? rules.partnerName : 'user';
  }

  // Create resolution
  const resolution: Resolution = {
    id: generateResolutionId(risk.id),
    riskId: risk.id,
    familyId: risk.familyId,
    action: 'send_message',
    autonomyLevel,

    // Recipient
    recipient,
    recipientChannel: 'push', // MVP: push notification only

    // Message will be generated by Language Actuator
    message: '', // Placeholder - filled by Language Actuator

    // Timing
    scheduledAt: Timestamp.fromDate(scheduledAt),
    vetoDeadline: Timestamp.fromDate(vetoDeadline),
    delayMinutes,

    // Status
    status: 'scheduled',
    createdAt: Timestamp.now(),
  };

  // Save resolution
  await db().collection('resolutions').doc(resolution.id).set(resolution);

  // Update risk status
  await db().collection('risks').doc(risk.id).update({
    status: 'resolving',
  });

  return { resolution, autonomyLevel };
}

// ============================================
// Autonomy Level Determination
// ============================================
//
// Moved to the Autonomy Governor Agent (../autonomy-governor). Resolution now
// delegates "how much autonomy" (decideAutonomyLevel) and outcome feedback
// (recordOutcome) to the governor, keeping this module focused on planning.

// ============================================
// Resolution Execution
// ============================================

export async function executeResolution(resolutionId: string): Promise<boolean> {
  const resolutionRef = db().collection('resolutions').doc(resolutionId);
  const doc = await resolutionRef.get();

  if (!doc.exists) {
    throw new Error(`Resolution ${resolutionId} not found`);
  }

  const resolution = doc.data() as Resolution;

  // Check if already executed or vetoed
  if (resolution.status !== 'scheduled') {
    console.log(`Resolution ${resolutionId} already ${resolution.status}`);
    return false;
  }

  // Check if past veto deadline
  const now = Timestamp.now();
  if (now.toMillis() < resolution.vetoDeadline.toMillis()) {
    console.log(`Resolution ${resolutionId} still within veto window`);
    return false;
  }

  // Execute the action (send push notification)
  console.log(`Executing resolution ${resolutionId}: Sending push to ${resolution.recipient}`);

  // Get the risk for context
  const riskDoc = await db().collection('risks').doc(resolution.riskId).get();
  const risk = riskDoc.data() as Risk;

  // Send push notification (title reflects the risk domain)
  const pushTitle =
    risk?.type === 'subscription_waste' ? 'Laxie 訂閱提醒' : 'Laxie 接送提醒';
  const pushResult = await sendPushToUser(resolution.recipient, {
    title: pushTitle,
    body: resolution.message,
    data: {
      type: 'resolution_executed',
      resolutionId: resolution.id,
      riskId: resolution.riskId,
      riskType: risk?.type || 'unknown',
    },
  });

  if (!pushResult.success) {
    console.warn(`Push notification failed: ${pushResult.error}`);
    // Continue execution even if push fails - log it for audit
  }

  // Update resolution status (filter out undefined values for Firestore)
  const pushResultData: Record<string, unknown> = {
    success: pushResult.success,
  };
  if (pushResult.messageId) pushResultData.messageId = pushResult.messageId;
  if (pushResult.error) pushResultData.error = pushResult.error;

  await resolutionRef.update({
    status: 'executed',
    executedAt: Timestamp.now(),
    pushResult: pushResultData,
  });

  // Update risk status
  await db().collection('risks').doc(resolution.riskId).update({
    status: 'resolved',
  });

  // Log the action
  await logAction(resolution, 'executed');

  // Autonomy Governor records the outcome against this category's ladder
  if (risk) {
    await recordOutcome(resolution, risk, false);
  }

  return true;
}

// ============================================
// Veto Handling
// ============================================

export async function vetoResolution(
  resolutionId: string,
  reason?: string
): Promise<boolean> {
  const resolutionRef = db().collection('resolutions').doc(resolutionId);
  const doc = await resolutionRef.get();

  if (!doc.exists) {
    throw new Error(`Resolution ${resolutionId} not found`);
  }

  const resolution = doc.data() as Resolution;

  // Check if can still be vetoed
  if (resolution.status !== 'scheduled') {
    console.log(`Cannot veto resolution ${resolutionId}: already ${resolution.status}`);
    return false;
  }

  const now = Timestamp.now();
  if (now.toMillis() > resolution.vetoDeadline.toMillis()) {
    console.log(`Cannot veto resolution ${resolutionId}: past deadline`);
    return false;
  }

  // Veto the resolution
  await resolutionRef.update({
    status: 'vetoed',
    vetoedAt: Timestamp.now(),
    vetoReason: reason || 'User vetoed',
  });

  // Update risk back to pending
  await db().collection('risks').doc(resolution.riskId).update({
    status: 'pending',
  });

  // Log the action
  await logAction(resolution, 'vetoed');

  // Autonomy Governor records the veto against this category's ladder
  const riskDoc = await db().collection('risks').doc(resolution.riskId).get();
  if (riskDoc.exists) {
    await recordOutcome(resolution, riskDoc.data() as Risk, true);
  }

  return true;
}

// ============================================
// Action Logging
// ============================================

async function logAction(
  resolution: Resolution,
  outcome: 'executed' | 'vetoed'
): Promise<void> {
  const risk = await db().collection('risks').doc(resolution.riskId).get();
  const riskData = risk.data() as Risk;

  const actionLog = {
    id: `log_${resolution.id}`,
    familyId: resolution.familyId,
    riskId: resolution.riskId,
    resolutionId: resolution.id,
    what: `${outcome === 'executed' ? 'Sent' : 'Did not send'} message to ${resolution.recipient}`,
    why: riskData.context.description,
    message: resolution.message,
    autonomyLevel: resolution.autonomyLevel,
    outcome,
    wasVetoed: outcome === 'vetoed',
    timestamp: Timestamp.now(),
  };

  await db().collection('actionLogs').doc(actionLog.id).set(actionLog);
}

// Trust metrics now live in the Autonomy Governor Agent
// (../autonomy-governor) — the single owner of the L0-L4 ladder.

// ============================================
// Query Functions
// ============================================

export async function getScheduledResolutions(
  familyId: string
): Promise<Resolution[]> {
  const snapshot = await db()
    .collection('resolutions')
    .where('familyId', '==', familyId)
    .where('status', '==', 'scheduled')
    .orderBy('scheduledAt')
    .get();

  return snapshot.docs.map((doc) => doc.data() as Resolution);
}

export async function getResolutionsForRisk(riskId: string): Promise<Resolution[]> {
  const snapshot = await db()
    .collection('resolutions')
    .where('riskId', '==', riskId)
    .get();

  return snapshot.docs.map((doc) => doc.data() as Resolution);
}

// ============================================
// Helper Functions
// ============================================

async function getFamilyRules(familyId: string): Promise<FamilyRules | null> {
  const doc = await db().collection('familyRules').doc(familyId).get();
  if (!doc.exists) {
    return null;
  }
  return doc.data() as FamilyRules;
}

function generateResolutionId(riskId: string): string {
  const timestamp = Date.now();
  return `res_${riskId}_${timestamp}`;
}
